Repository discordrb/discordrb, pull requests merged in 2018-09, with the labels that each got.

#530 Add "Priority Speaker" as bit 8
  lib/discordrb/permissions.rb
Labels: api-support

#528 Enable SSLSocket certificate verification, enforce TLSv1.2
  lib/discordrb/gateway.rb
Labels: security

#531 Clarify event handler documentation for #voice_state_update, #member_…
  lib/discordrb/container.rb
Labels: documentation

#533 Add frozen_string_literal magic comment to files where missing
  lib/discordrb/api/channel.rb
  lib/discordrb/api/invite.rb
  lib/discordrb/api/server.rb
  lib/discordrb/api/user.rb
  lib/discordrb/api/webhook.rb
  lib/discordrb/gateway.rb
  lib/discordrb/webhooks/builder.rb
  lib/discordrb/webhooks/client.rb
  lib/discordrb/webhooks/embeds.rb
Labels: code-style

#524 Implement CommandAlias
  lib/discordrb/commands/command_bot.rb
  lib/discordrb/commands/container.rb
  lib/discordrb/commands/parser.rb
Labels: breaking-change, commands

#534 Add send_messages argument to Server#default_channel
  lib/discordrb/data.rb
Labels: bug, enhancement

#535 Only cache member roles that exist on the server
  lib/discordrb/data.rb
Labels: bug, caching

#544 Update ffi dependency to >= 1.9.24
  discordrb.gemspec
Labels: security, windows
