Repository discordrb/discordrb, pull requests merged in 2018-05, with the labels that each got.

#489 Update to new Code Climate test reporter
  .travis.yml
  Gemfile
  discordrb.gemspec
Labels: ci

#494 Add EventContainer#server_role_create,delete,update
  lib/discordrb/container.rb
Labels: enhancement, events

#486 Added `details` field to Events::PlayingEvent
  lib/discordrb/events/presence.rb
Labels: api-support, enhancement

#488 Update cached role on ROLE_CREATE
  lib/discordrb/bot.rb
Labels: bug, caching
