Repository discordrb/discordrb, pull requests merged in 2018-08, with the labels that each got.

#520 Remove Module from Specs
  spec/bot_spec.rb
  spec/data_spec.rb
  spec/event_spec.rb
  spec/main_spec.rb
  spec/permissions_spec.rb
Labels: code-style, specs

#521 Update Bot#run documentation
  lib/discordrb/bot.rb
Labels: breaking-change, documentation

#523 Embed#colour= accepts #to_i, add ColourRGB#to_i
  lib/discordrb/data.rb
  lib/discordrb/webhooks/embeds.rb
Labels: enhancement

#525 Add channel mention support to Bot#parse_mention
  lib/discordrb/bot.rb
Labels: enhancement

#527 Support zlib-stream gateway compression
  lib/discordrb/bot.rb
  lib/discordrb/commands/command_bot.rb
  lib/discordrb/gateway.rb
Labels: api-support, enhancement
