Repository discordrb/discordrb, pull requests merged in 2018-07, with the labels that each got.

#511 Grammar/spelling improvements for the docs in data.rb.
  lib/discordrb/data.rb
Labels: documentation

#503 Update required Ruby version in the README.
  README.md
Labels: documentation

#515 Add changelog link to gem metadata
  discordrb.gemspec
Labels: enhancement

#469 Alternative for restricting commands to some roles instead of all of required_roles
  lib/discordrb/commands/command_bot.rb
  lib/discordrb/commands/container.rb
  lib/discordrb/commands/parser.rb
  spec/commands_spec.rb
Labels: commands, enhancement

#514 Call events over a copy of event handlers
  lib/discordrb/bot.rb
Labels: bug, events

#517 Fixes issue #501
  lib/discordrb/commands/parser.rb
Labels: bug, commands
