Repository discordrb/discordrb, pull requests merged in 2018-10, with the labels that each got.

#573 Added Discord's new slowmode
  lib/discordrb/api/channel.rb
  lib/discordrb/api/server.rb
  lib/discordrb/data.rb
  spec/data/text_channel.json
  spec/data_spec.rb
Labels: api-support, enhancement

#574 Check against the name of a user's game in PRESENCE_UPDATE
  lib/discordrb/bot.rb
Labels: bug, events

#575 Fix attachment.id => nil
  lib/discordrb/data.rb
Labels: bug

#578 Move unavailable server warnings to seperate method
  lib/discordrb/bot.rb
Labels: enhancement, logging

#487 Appease the RuboCop
  .rubocop.yml
  .travis.yml
  CHANGELOG.md
  Gemfile
  Rakefile
  bin/console
  discordrb-webhooks.gemspec
  discordrb.gemspec
  examples/awaits.rb
  examples/commands.rb
  examples/eval.rb
  examples/ping.rb
  examples/ping_with_respond_time.rb
  examples/pm_send.rb
  examples/prefix_proc.rb
  examples/shutdown.rb
  examples/voice_send.rb
  lib/discordrb/api.rb
  lib/discordrb/api/channel.rb
  lib/discordrb/api/server.rb
  lib/discordrb/bot.rb
  lib/discordrb/cache.rb
  lib/discordrb/commands/command_bot.rb
  lib/discordrb/commands/container.rb
  lib/discordrb/commands/parser.rb
  lib/discordrb/commands/rate_limiter.rb
  lib/discordrb/container.rb
  lib/discordrb/data.rb
  lib/discordrb/errors.rb
  lib/discordrb/events/members.rb
  lib/discordrb/events/message.rb
  lib/discordrb/events/voice_state_update.rb
  lib/discordrb/gateway.rb
  lib/discordrb/logger.rb
  lib/discordrb/permissions.rb
  lib/discordrb/version.rb
  lib/discordrb/voice/encoder.rb
  lib/discordrb/voice/network.rb
  lib/discordrb/voice/voice_bot.rb
  lib/discordrb/webhooks/builder.rb
  lib/discordrb/webhooks/client.rb
  lib/discordrb/webhooks/embeds.rb
  lib/discordrb/webhooks/version.rb
  spec/api_mock_spec.rb
  spec/bot_spec.rb
  spec/commands_spec.rb
  spec/data_spec.rb
  spec/errors_spec.rb
  spec/event_spec.rb
  spec/helpers_spec.rb
  spec/logger_spec.rb
  spec/main_spec.rb
  spec/mock/api_mock.rb
  spec/permissions_spec.rb
  spec/rate_limiter_spec.rb
  spec/spec_helper.rb
  spec/webhooks_spec.rb
Labels: breaking-change, code-style

#538 Update deps
  CHANGELOG.md
  discordrb.gemspec
Labels: code-style

#526 Add Bot#parse_mentions
  CHANGELOG.md
  lib/discordrb/bot.rb
  spec/bot_spec.rb
Labels: enhancement, utility
