Repository discordrb/discordrb, pull requests merged in 2018-06, with the labels that each got.

#504 Modify the Changelog to follow the Keep a Changelog format.
  CHANGELOG.md
Labels: documentation

#505 Add attr_reader :server to Role
  lib/discordrb/data.rb
Labels: enhancement

#460 Document `discordrb-webhooks` in README
  README.md
Labels: documentation

#499 Add blocking await methods
  lib/discordrb/bot.rb
  lib/discordrb/data.rb
Labels: enhancement, utility

#497 Add Channel#sort_after
  lib/discordrb/data.rb
  spec/data_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#508 Fix server icon uploading
  lib/discordrb/data.rb
Labels: bug
