Repository discordrb/discordrb, pull requests merged in 2019-04, with the labels that each got.

#623 Tighten RuboCop dependency again
  discordrb.gemspec
Labels: ci

#622 Clarify API.bot_name
  CHANGELOG.md
  lib/discordrb/api.rb
Labels: documentation

#617 Removing old logic regarding nsfw channels
  CHANGELOG.md
  lib/discordrb/data/channel.rb
Labels: api-change, bug, caching

#615 Implement Paginator in Message#reacted_with
  CHANGELOG.md
  lib/discordrb/api/channel.rb
  lib/discordrb/data/message.rb
Labels: api-support, enhancement

#618 Add news? and store?
  CHANGELOG.md
  lib/discordrb/data/channel.rb
  lib/discordrb/data/server.rb
Labels: api-support
