Repository discordrb/discordrb, pull requests merged in 2019-11, with the labels that each got.

#625 Fix VoiceStateUpdateEvent handler matching
  CHANGELOG.md
  lib/discordrb/events/voice_state_update.rb
Labels: bug, events

#634 Prepare deprecated command aliases for removal
  lib/discordrb/commands/container.rb
Labels: commands

#635 Add block to await! API
  CHANGELOG.md
  lib/discordrb/bot.rb
  lib/discordrb/data/channel.rb
  lib/discordrb/data/message.rb
  lib/discordrb/data/user.rb
Labels: enhancement, utility

#636 Update RuboCop and rbnacl
  CHANGELOG.md
  discordrb.gemspec
Labels: code-style

#637 Add #create_webhook method to create a webhook in a channel
  CHANGELOG.md
  lib/discordrb/data/channel.rb
Labels: api-support, enhancement

#641 Remove rbnacl gem dependency
  .travis.yml
  CHANGELOG.md
  discordrb.gemspec
  lib/discordrb/bot.rb
  lib/discordrb/voice/network.rb
  lib/discordrb/voice/sodium.rb
  spec/sodium_spec.rb
Labels: voice

#642 Fix to_reaction not behaving well for unicode emoji
  CHANGELOG.md
  lib/discordrb/data/emoji.rb
  spec/data/emoji_spec.rb
Labels: bug

#643 Return `nil` on 204 response
  CHANGELOG.md
  lib/discordrb/data/server.rb
Labels: bug

#644 Update VoiceUDP to use `ip` in `READY` payload
  CHANGELOG.md
  lib/discordrb/voice/network.rb
Labels: api-change, voice

#646 Exclude the end value, to make more efficient code
  CHANGELOG.md
  lib/discordrb.rb
Labels: enhancement

#652 Clean up pre-2.4 code
  CHANGELOG.md
  lib/discordrb/events/raw.rb
  lib/discordrb/gateway.rb
Labels: breaking-change

#656 Parse Integer arguments in base 10
  CHANGELOG.md
  examples/prefix_proc.rb
  lib/discordrb/commands/command_bot.rb
Labels: bug, commands

#660 Add stream permission
  CHANGELOG.md
  lib/discordrb/permissions.rb
Labels: api-support, enhancement

#661 Update github links after repo transfer
  CHANGELOG.md
  README.md
  discordrb-webhooks.gemspec
  discordrb.gemspec
  examples/ping.rb
  lib/discordrb/api.rb
  lib/discordrb/commands/command_bot.rb
  lib/discordrb/data/member.rb
  lib/discordrb/voice/network.rb
Labels: documentation

#647 Fix @see link on CommandBot#init
  CHANGELOG.md
  lib/discordrb/commands/command_bot.rb
Labels: bug, documentation

#662 Fix message split in #split_message
  lib/discordrb.rb
  spec/main_spec.rb
Labels: enhancement, utility

#638 Update Server class to support Nitro Boost features
  CHANGELOG.md
  lib/discordrb/api.rb
  lib/discordrb/bot.rb
  lib/discordrb/data/member.rb
  lib/discordrb/data/server.rb
Labels: api-support, enhancement

#653 Implement ms ratelimit precision
  lib/discordrb/api.rb
Labels: api-change

#663 Fix for not rescued NoMethodError on bot kick (#619)
  lib/discordrb/bot.rb
Labels: bug

#665 Remove plain voice connections
  lib/discordrb/bot.rb
  lib/discordrb/voice/network.rb
  lib/discordrb/voice/voice_bot.rb
  spec/bot_spec.rb
Labels: api-change, voice

#669 Add view_server_insights permission
  lib/discordrb/permissions.rb
Labels: api-support

#680 Change getc to readpartial
  lib/discordrb/gateway.rb
Labels: performance
