Repository discordrb/discordrb, pull requests merged in 2019-01, with the labels that each got.

#591 Fix Travis
  CHANGELOG.md
  discordrb.gemspec
Labels: ci

#592 Adding position to API::Server.create_channel and Server.create_channel
  CHANGELOG.md
  lib/discordrb/api/server.rb
  lib/discordrb/data/server.rb
Labels: api-support, enhancement

#597 Add Server#bot
  CHANGELOG.md
  lib/discordrb/data/server.rb
Labels: enhancement
