Repository discordrb/discordrb, pull requests merged in 2019-03, with the labels that each got.

#595 Add Discordrb::Server#add_emoji and add roles parameter to Discordrb:…
  CHANGELOG.md
  lib/discordrb/api/server.rb
  lib/discordrb/data/server.rb
Labels: api-support, enhancement

#606 Add `spoiler` kwarg to methods that send_files
  CHANGELOG.md
  lib/discordrb/bot.rb
  lib/discordrb/data/channel.rb
  lib/discordrb/data/user.rb
  lib/discordrb/events/message.rb
  spec/bot_spec.rb
  spec/event_spec.rb
Labels: enhancement

#609 Sort roles by position in permissions calculation
  CHANGELOG.md
  lib/discordrb/permissions.rb
  spec/permissions_spec.rb
Labels: bug

#579 Implement Paginator utility
  CHANGELOG.md
  lib/discordrb/data.rb
  lib/discordrb/paginator.rb
  spec/paginator_spec.rb
Labels: enhancement, utility

#611 Raise DisconnectEvent in handle_close
  CHANGELOG.md
  lib/discordrb/gateway.rb
Labels: bug, events

#612 Adding MessageUpdateEvent
  CHANGELOG.md
  lib/discordrb/bot.rb
  lib/discordrb/container.rb
  lib/discordrb/events/message.rb
Labels: enhancement, events

#614 Add `Message#server`
  CHANGELOG.md
  lib/discordrb/data/message.rb
Labels: enhancement
