Repository discordrb/discordrb, pull requests merged in 2019-05, with the labels that each got.

#596 Fix custom emoji reactions with the same name from being discarded
  lib/discordrb/data/message.rb
Labels: breaking-change, bug

#616 Remove #resolve_id duck typing
  lib/discordrb/bot.rb
  lib/discordrb/colour_rgb.rb
  lib/discordrb/commands/container.rb
  lib/discordrb/commands/rate_limiter.rb
  lib/discordrb/container.rb
  lib/discordrb/data/audit_logs.rb
  lib/discordrb/data/channel.rb
  lib/discordrb/data/member.rb
  lib/discordrb/data/message.rb
  lib/discordrb/data/overwrite.rb
  lib/discordrb/data/role.rb
  lib/discordrb/data/server.rb
  lib/discordrb/data/webhook.rb
  lib/discordrb/webhooks/embeds.rb
Labels: documentation

#626 Add convenience methods for getting bot and non bot members
  lib/discordrb/data/server.rb
Labels: enhancement, utility

#627 Send argument number errors with usage as a single message
  lib/discordrb/commands/parser.rb
Labels: commands

#628 Fix nsfw value not being passed to API call
  lib/discordrb/data/channel.rb
Labels: bug

#629 Fix issue with implicit return on #split_send
  lib/discordrb/data/channel.rb
Labels: enhancement, utility

#633 Give up reconnection on a fatal close code
  CHANGELOG.md
  lib/discordrb/gateway.rb
Labels: enhancement, error-handling

#624 RuboCop Improvements
  .rubocop.yml
  CHANGELOG.md
  discordrb.gemspec
  lib/discordrb/bot.rb
  lib/discordrb/commands/parser.rb
Labels: ci, code-style
