Repository discordrb/discordrb, pull requests merged in 2019-12, with the labels that each got.

#679 Add dnd? method for User
  CHANGELOG.md
  lib/discordrb/data/user.rb
Labels: api-support, documentation

#678 Channel docs update
  lib/discordrb/data/channel.rb
Labels: documentation

#674 Update VoiceBot#channel on VOICE_STATE_UPDATE
  lib/discordrb/bot.rb
  lib/discordrb/voice/voice_bot.rb
Labels: bug, caching, voice

#683 Update webhook to include type field
  lib/discordrb/data/webhook.rb
Labels: api-change, breaking-change
